# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SED Blog
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  The Systems Engineering Design group at Chalmers studies the product development process and its participants in product developing companies in order to understand their problems and needs. This knowledge gained is then transformed into better work procedures, development methods and computer-based tools. A special interest is platform-based development, which is a widely adopted strategy for balancing the conflict between reuse and demands on customization. 
  The aim of the research conducted within this theme is to significantly contribute to a new system family based platform description approach that, in a PLM environment, will provide a ground for reuse of assets in terms of knowledge in all product development phases as well as in production, i.e. from early requirement specification and concept development phases to the final detail system design phase and in production.
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.systemsengineering.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SED_Lab
github_username:  sed-group

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
